locales:
  esu:
    name: Central Alaskan Yup'ik Keyboards
    description: >-
      Mobile OS keyboards for the Central Alaskan Yup'ik language from the Divvun group
      at UiT.
  en:
    name: Central Alaskan Yup'ik Keyboards
    description: >-
      Mobile OS keyboards for the Central Alaskan Yup'ik language from the Divvun group
      at UiT.
  nb:
    name: Central Alaskan Yup'ik tastatur
    description: Mobiltastatur for Central Alaskan Yup'ik fra Divvun-gruppa.
author: 'The Divvun Group, UiT Norgga 치rktala코 universitehta'
copyright: (c) 2017 Divvun/Giellatekno/UiT
email: feedback@divvun.no
organisation: UiT Norgga 치rktala코 universitehta
